export type PurchaseOrderItem = {
  id: string;
  code: string;
  subPurchaseOrderId: string;
  wareCode: string;
  amount: number;
  numberOfBlanks: number;
  longitudinalCutCount: number;
  runningLength: number;
  faceLayerPaperWeight: number | null;
  EFlutePaperWeight: number | null;
  EBLinerLayerPaperWeight: number | null;
  BFlutePaperWeight: number | null;
  BACLinerLayerPaperWeight: number | null;
  ACFlutePaperWeight: number | null;
  backLayerPaperWeight: number | null;
  totalVolume: number;
  totalWeight: number;
  status: string;
  note: string;
};
