export type Ware = {
  id: string;
  code: string;
  unitPrice: number;
  fluteCombinationCode: string;
  wareWidth: number;
  wareLength: number;
  wareHeight: number | null;
  wareManufacturingProcessType: string;
  warePerBlankAdjustment: number | null;
  flapAdjustment: number | null;
  flapOverlapAdjustment: number | null;
  crossCutCountAdjustment: number | null;
  warePerBlank: number;
  blankWidth: number;
  blankLength: number;
  flapLength: number | null;
  margin: number;
  paperWidth: number;
  crossCutCount: number;
  faceLayerPaperType: string | null;
  EFlutePaperType: string | null;
  EBLinerLayerPaperType: string | null;
  BFlutePaperType: string | null;
  BACLinerLayerPaperType: string | null;
  ACFlutePaperType: string | null;
  backLayerPaperType: string | null;
  volume: number;
  warePerSet: number;
  warePerCombinedSet: number;
  horizontalWareSplit: number;
  printColors: string[];
  typeOfPrinter: string | null;
  manufacturingProcesses: string[];
  note: string;
};
